# Generated by Django 3.2.12 on 2022-09-27 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key='user_uid',
                                       serialize=False, to=settings.AUTH_USER_MODEL,
                                       verbose_name='Профиль пользователя'),
        ),
    ]
