# Generated by Django 3.2.12 on 2022-05-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='aboutMe',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tagline',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, verbose_name='о себе'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='langs',
            field=models.CharField(blank=True, default='RU', max_length=5, verbose_name='язык'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'М'), ('W', 'Ж')], max_length=2, verbose_name='пол'),
        ),
    ]
