# Generated by Django 3.2.12 on 2022-05-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='langs',
            field=models.CharField(blank=True, default='RU', max_length=100, verbose_name='язык'),
        ),
    ]
