# Generated by Django 3.2.12 on 2022-09-27 13:30

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя или никнейм комментатора')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта комментатора')),
                ('body', models.TextField(verbose_name='Тело комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Комментарий создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Комментарий изменен')),
                ('active', models.BooleanField(default=True, verbose_name='Статус комментария')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок поста')),
                ('image', models.ImageField(upload_to='blogs_post_images', verbose_name='Изображение поста')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, unique_for_date='publish',
                                          verbose_name='URL')),
                ('body', models.TextField(verbose_name='Содержимое поста')),
                ('publish',
                 models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время публикации поста')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания поста')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения поста')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft',
                                            max_length=10, verbose_name='Статус поста')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
