# Generated by Django 3.2.12 on 2022-05-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Ваш комментарий'),
        ),
    ]
