# Generated by Django 3.2.12 on 2022-05-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blogs', '0003_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Имя'),
        ),
    ]
