# Generated by Django 3.2.12 on 2022-05-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blogs', '0005_auto_20220519_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Ваш комментарий'),
        ),
    ]
