# Generated by Django 3.2.12 on 2022-05-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blogs', '0007_auto_20220519_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name='Содержимое поста'),
        ),
    ]
