# Generated by Django 3.2.12 on 2022-05-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blogs', '0008_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя или никнейм'),
        ),
    ]
