# Generated by Django 3.2.12 on 2022-09-27 13:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество товаров в корзине')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product',
                                              verbose_name='Продукты в корзине')),
            ],
        ),
    ]
