# Generated by Django 3.2.12 on 2022-05-23 23:36

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('baskets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basket',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
