# Generated by Django 3.2.12 on 2022-05-25 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('baskets', '0002_alter_basket_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basket',
            managers=[
            ],
        ),
    ]
