# Generated by Django 3.2.12 on 2022-05-25 16:28

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('baskets', '0003_alter_basket_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basket',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
