# Generated by Django 3.2.12 on 2022-05-25 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('baskets', '0006_auto_20220525_2009'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basket',
            managers=[
            ],
        ),
    ]
