# Generated by Django 3.2.12 on 2022-05-18 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('products', '0004_product_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Обновлен')),
                ('paid', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('status', models.CharField(
                    choices=[('FM', 'Формируется'), ('STP', 'Отправлен в обработку'), ('PD', 'Оплачен'),
                             ('PRD', 'Обрабатывается'), ('RDY', 'Готов к выдачи'), ('CNC', 'Отмена заказа')],
                    default='FM', max_length=50, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems',
                                            to='orders.order', verbose_name='заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product',
                                              verbose_name='продукты')),
            ],
        ),
    ]
