# Generated by Django 4.0.3 on 2022-03-28 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='description',
        ),
    ]
