# Generated by Django 3.2.12 on 2022-05-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0004_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
